title: Pixel art
hero_image: images/banner.png
description: Make some colourful pixel art!
version: 4
listed: false
copyedit: false
last_tested: "2024-06-27"
landing: true
steps:
  - title: Make the grid
  - title: Style the grid area
    completion:
      - engaged
  - title: Make the grid clickable
  - title: Change the paint colour
  - title: Add a palette
  - title: Pick the paint
  - title: Choose a palette colour
    completion:
      - internal
  - title: Challenges
    challenge: true
