title: Pixel art
hero_image: images/banner.png
description: Make some colourful pixel art!
version: 4
listed: false
copyedit: false
last_tested: "2024-06-27"
steps:
  - title: Step 1
    completion:
      - engaged
  - title: Step 2
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8 
    completion:
      - internal
  - title: Step 9
 
